version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  # For npm dependency updates, we assume there is a high probability that
  # "some fix (related to potential bugs) was made without fundamentally changing
  # behavior". We use the "fix" prefix to promote patch version increments,
  # erring on the safe side.
  - package-ecosystem: "npm"
    directory: "/.github/actions/exec-merge"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
